apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-cd-pipeline
  labels: {}
description: cd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev-pipeline
    deployParameters:
    - values:
      matchTargetLabels:
        app: frontend-api
    - values:
      matchTargetLabels:
        app: dev-pipeline