apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-cd-pipeline
  labels: {}
description: cd delivery pipeline
serialPipeline:
  stages:
  - targetId: $dev-pipeline
  - targetId: prod-pipeline
